aastinky { program defaultwall#VERTEXLIT diffusemap textures/doom/aastinky { rgbgen vertex alphagen vertex } }
ashwall { program defaultwall#VERTEXLIT diffusemap textures/doom/ashwall { rgbgen vertex alphagen vertex } }
bigdoor1 { program defaultwall#VERTEXLIT diffusemap textures/doom/bigdoor1 { rgbgen vertex alphagen vertex } }
bigdoor2 { program defaultwall#VERTEXLIT diffusemap textures/doom/bigdoor2 { rgbgen vertex alphagen vertex } }
bigdoor3 { program defaultwall#VERTEXLIT diffusemap textures/doom/bigdoor3 { rgbgen vertex alphagen vertex } }
bigdoor4 { program defaultwall#VERTEXLIT diffusemap textures/doom/bigdoor4 { rgbgen vertex alphagen vertex } }
bigdoor5 { program defaultwall#VERTEXLIT diffusemap textures/doom/bigdoor5 { rgbgen vertex alphagen vertex } }
bigdoor6 { program defaultwall#VERTEXLIT diffusemap textures/doom/bigdoor6 { rgbgen vertex alphagen vertex } }
bigdoor7 { program defaultwall#VERTEXLIT diffusemap textures/doom/bigdoor7 { rgbgen vertex alphagen vertex } }
blodgr1 { program defaultwall#VERTEXLIT diffusemap textures/doom/blodgr1 { rgbgen vertex alphagen vertex } }
blodgr2 { program defaultwall#VERTEXLIT diffusemap textures/doom/blodgr2 { rgbgen vertex alphagen vertex } }
blodgr3 { program defaultwall#VERTEXLIT diffusemap textures/doom/blodgr3 { rgbgen vertex alphagen vertex } }
blodgr4 { program defaultwall#VERTEXLIT diffusemap textures/doom/blodgr4 { rgbgen vertex alphagen vertex } }
blodrip1 { program defaultwall#VERTEXLIT diffusemap textures/doom/blodrip1 { rgbgen vertex alphagen vertex } }
blodrip2 { program defaultwall#VERTEXLIT diffusemap textures/doom/blodrip2 { rgbgen vertex alphagen vertex } }
blodrip3 { program defaultwall#VERTEXLIT diffusemap textures/doom/blodrip3 { rgbgen vertex alphagen vertex } }
blodrip4 { program defaultwall#VERTEXLIT diffusemap textures/doom/blodrip4 { rgbgen vertex alphagen vertex } }
blood1 { program defaultwall#VERTEXLIT diffusemap textures/doom/blood1 { rgbgen vertex alphagen vertex } }
blood2 { program defaultwall#VERTEXLIT diffusemap textures/doom/blood2 { rgbgen vertex alphagen vertex } }
blood3 { program defaultwall#VERTEXLIT diffusemap textures/doom/blood3 { rgbgen vertex alphagen vertex } }
brnbigc { program defaultwall#VERTEXLIT diffusemap textures/doom/brnbigc { rgbgen vertex alphagen vertex } }
brnbigl { program defaultwall#VERTEXLIT diffusemap textures/doom/brnbigl { rgbgen vertex alphagen vertex } }
brnbigr { program defaultwall#VERTEXLIT diffusemap textures/doom/brnbigr { rgbgen vertex alphagen vertex } }
brnpois { program defaultwall#VERTEXLIT diffusemap textures/doom/brnpois { rgbgen vertex alphagen vertex } }
brnpois2 { program defaultwall#VERTEXLIT diffusemap textures/doom/brnpois2 { rgbgen vertex alphagen vertex } }
brnsmal1 { program defaultwall#VERTEXLIT diffusemap textures/doom/brnsmal1 { rgbgen vertex alphagen vertex } }
brnsmal2 { program defaultwall#VERTEXLIT diffusemap textures/doom/brnsmal2 { rgbgen vertex alphagen vertex } }
brnsmalc { program defaultwall#VERTEXLIT diffusemap textures/doom/brnsmalc { rgbgen vertex alphagen vertex } }
brnsmall { program defaultwall#VERTEXLIT diffusemap textures/doom/brnsmall { rgbgen vertex alphagen vertex } }
brnsmalr { program defaultwall#VERTEXLIT diffusemap textures/doom/brnsmalr { rgbgen vertex alphagen vertex } }
brovine { program defaultwall#VERTEXLIT diffusemap textures/doom/brovine { rgbgen vertex alphagen vertex } }
brovine2 { program defaultwall#VERTEXLIT diffusemap textures/doom/brovine2 { rgbgen vertex alphagen vertex } }
brown1 { program defaultwall#VERTEXLIT diffusemap textures/doom/brown1 { rgbgen vertex alphagen vertex } }
brown144 { program defaultwall#VERTEXLIT diffusemap textures/doom/brown144 { rgbgen vertex alphagen vertex } }
brown96 { program defaultwall#VERTEXLIT diffusemap textures/doom/brown96 { rgbgen vertex alphagen vertex } }
browngrn { program defaultwall#VERTEXLIT diffusemap textures/doom/browngrn { rgbgen vertex alphagen vertex } }
brownhug { program defaultwall#VERTEXLIT diffusemap textures/doom/brownhug { rgbgen vertex alphagen vertex } }
brownpip { program defaultwall#VERTEXLIT diffusemap textures/doom/brownpip { rgbgen vertex alphagen vertex } }
brownwel { program defaultwall#VERTEXLIT diffusemap textures/doom/brownwel { rgbgen vertex alphagen vertex } }
ceil1_1 { program defaultwall#VERTEXLIT diffusemap textures/doom/ceil1_1 { rgbgen vertex alphagen vertex } }
ceil1_2 { program defaultwall#VERTEXLIT diffusemap textures/doom/ceil1_2 { rgbgen vertex alphagen vertex } }
ceil1_3 { program defaultwall#VERTEXLIT diffusemap textures/doom/ceil1_3 { rgbgen vertex alphagen vertex } }
ceil3_1 { program defaultwall#VERTEXLIT diffusemap textures/doom/ceil3_1 { rgbgen vertex alphagen vertex } }
ceil3_2 { program defaultwall#VERTEXLIT diffusemap textures/doom/ceil3_2 { rgbgen vertex alphagen vertex } }
ceil3_3 { program defaultwall#VERTEXLIT diffusemap textures/doom/ceil3_3 { rgbgen vertex alphagen vertex } }
ceil3_4 { program defaultwall#VERTEXLIT diffusemap textures/doom/ceil3_4 { rgbgen vertex alphagen vertex } }
ceil3_5 { program defaultwall#VERTEXLIT diffusemap textures/doom/ceil3_5 { rgbgen vertex alphagen vertex } }
ceil3_6 { program defaultwall#VERTEXLIT diffusemap textures/doom/ceil3_6 { rgbgen vertex alphagen vertex } }
ceil4_1 { program defaultwall#VERTEXLIT diffusemap textures/doom/ceil4_1 { rgbgen vertex alphagen vertex } }
ceil4_2 { program defaultwall#VERTEXLIT diffusemap textures/doom/ceil4_2 { rgbgen vertex alphagen vertex } }
ceil4_3 { program defaultwall#VERTEXLIT diffusemap textures/doom/ceil4_3 { rgbgen vertex alphagen vertex } }
ceil5_1 { program defaultwall#VERTEXLIT diffusemap textures/doom/ceil5_1 { rgbgen vertex alphagen vertex } }
ceil5_2 { program defaultwall#VERTEXLIT diffusemap textures/doom/ceil5_2 { rgbgen vertex alphagen vertex } }
cement1 { program defaultwall#VERTEXLIT diffusemap textures/doom/cement1 { rgbgen vertex alphagen vertex } }
cement2 { program defaultwall#VERTEXLIT diffusemap textures/doom/cement2 { rgbgen vertex alphagen vertex } }
cement3 { program defaultwall#VERTEXLIT diffusemap textures/doom/cement3 { rgbgen vertex alphagen vertex } }
cement4 { program defaultwall#VERTEXLIT diffusemap textures/doom/cement4 { rgbgen vertex alphagen vertex } }
cement5 { program defaultwall#VERTEXLIT diffusemap textures/doom/cement5 { rgbgen vertex alphagen vertex } }
cement6 { program defaultwall#VERTEXLIT diffusemap textures/doom/cement6 { rgbgen vertex alphagen vertex } }
cempois { program defaultwall#VERTEXLIT diffusemap textures/doom/cempois { rgbgen vertex alphagen vertex } }
comp01 { program defaultwall#VERTEXLIT diffusemap textures/doom/comp01 { rgbgen vertex alphagen vertex } }
comp2 { program defaultwall#VERTEXLIT diffusemap textures/doom/comp2 { rgbgen vertex alphagen vertex } }
compblue { program defaultwall#VERTEXLIT diffusemap textures/doom/compblue { rgbgen vertex alphagen vertex } }
compohso { program defaultwall#VERTEXLIT diffusemap textures/doom/compohso { rgbgen vertex alphagen vertex } }
compspan { program defaultwall#VERTEXLIT diffusemap textures/doom/compspan { rgbgen vertex alphagen vertex } }
compsta1 { program defaultwall#VERTEXLIT diffusemap textures/doom/compsta1 { rgbgen vertex alphagen vertex } }
compsta2 { program defaultwall#VERTEXLIT diffusemap textures/doom/compsta2 { rgbgen vertex alphagen vertex } }
comptall { program defaultwall#VERTEXLIT diffusemap textures/doom/comptall { rgbgen vertex alphagen vertex } }
comptile { program defaultwall#VERTEXLIT diffusemap textures/doom/comptile { rgbgen vertex alphagen vertex } }
compute1 { program defaultwall#VERTEXLIT diffusemap textures/doom/compute1 { rgbgen vertex alphagen vertex } }
compute2 { program defaultwall#VERTEXLIT diffusemap textures/doom/compute2 { rgbgen vertex alphagen vertex } }
compute3 { program defaultwall#VERTEXLIT diffusemap textures/doom/compute3 { rgbgen vertex alphagen vertex } }
compwerd { program defaultwall#VERTEXLIT diffusemap textures/doom/compwerd { rgbgen vertex alphagen vertex } }
cons1_1 { program defaultwall#VERTEXLIT diffusemap textures/doom/cons1_1 { rgbgen vertex alphagen vertex } }
cons1_5 { program defaultwall#VERTEXLIT diffusemap textures/doom/cons1_5 { rgbgen vertex alphagen vertex } }
cons1_7 { program defaultwall#VERTEXLIT diffusemap textures/doom/cons1_7 { rgbgen vertex alphagen vertex } }
crate1 { program defaultwall#VERTEXLIT diffusemap textures/doom/crate1 { rgbgen vertex alphagen vertex } }
crate2 { program defaultwall#VERTEXLIT diffusemap textures/doom/crate2 { rgbgen vertex alphagen vertex } }
cratelit { program defaultwall#VERTEXLIT diffusemap textures/doom/cratelit { rgbgen vertex alphagen vertex } }
cratiny { program defaultwall#VERTEXLIT diffusemap textures/doom/cratiny { rgbgen vertex alphagen vertex } }
cratop1 { program defaultwall#VERTEXLIT diffusemap textures/doom/cratop1 { rgbgen vertex alphagen vertex } }
cratop2 { program defaultwall#VERTEXLIT diffusemap textures/doom/cratop2 { rgbgen vertex alphagen vertex } }
cratwide { program defaultwall#VERTEXLIT diffusemap textures/doom/cratwide { rgbgen vertex alphagen vertex } }
dem1_1 { program defaultwall#VERTEXLIT diffusemap textures/doom/dem1_1 { rgbgen vertex alphagen vertex } }
dem1_2 { program defaultwall#VERTEXLIT diffusemap textures/doom/dem1_2 { rgbgen vertex alphagen vertex } }
dem1_3 { program defaultwall#VERTEXLIT diffusemap textures/doom/dem1_3 { rgbgen vertex alphagen vertex } }
dem1_4 { program defaultwall#VERTEXLIT diffusemap textures/doom/dem1_4 { rgbgen vertex alphagen vertex } }
dem1_5 { program defaultwall#VERTEXLIT diffusemap textures/doom/dem1_5 { rgbgen vertex alphagen vertex } }
dem1_6 { program defaultwall#VERTEXLIT diffusemap textures/doom/dem1_6 { rgbgen vertex alphagen vertex } }
door1 { program defaultwall#VERTEXLIT diffusemap textures/doom/door1 { rgbgen vertex alphagen vertex } }
door3 { program defaultwall#VERTEXLIT diffusemap textures/doom/door3 { rgbgen vertex alphagen vertex } }
doorblu { program defaultwall#VERTEXLIT diffusemap textures/doom/doorblu { rgbgen vertex alphagen vertex } }
doorblu2 { program defaultwall#VERTEXLIT diffusemap textures/doom/doorblu2 { rgbgen vertex alphagen vertex } }
doorhi { program defaultwall#VERTEXLIT diffusemap textures/doom/doorhi { rgbgen vertex alphagen vertex } }
doorred { program defaultwall#VERTEXLIT diffusemap textures/doom/doorred { rgbgen vertex alphagen vertex } }
doorred2 { program defaultwall#VERTEXLIT diffusemap textures/doom/doorred2 { rgbgen vertex alphagen vertex } }
doorstop { program defaultwall#VERTEXLIT diffusemap textures/doom/doorstop { rgbgen vertex alphagen vertex } }
doortrak { program defaultwall#VERTEXLIT diffusemap textures/doom/doortrak { rgbgen vertex alphagen vertex } }
dooryel { program defaultwall#VERTEXLIT diffusemap textures/doom/dooryel { rgbgen vertex alphagen vertex } }
dooryel2 { program defaultwall#VERTEXLIT diffusemap textures/doom/dooryel2 { rgbgen vertex alphagen vertex } }
exitdoor { program defaultwall#VERTEXLIT diffusemap textures/doom/exitdoor { rgbgen vertex alphagen vertex } }
exitsign { program defaultwall#VERTEXLIT diffusemap textures/doom/exitsign { rgbgen vertex alphagen vertex } }
exitston { program defaultwall#VERTEXLIT diffusemap textures/doom/exitston { rgbgen vertex alphagen vertex } }
fireblu1 { program defaultwall#VERTEXLIT diffusemap textures/doom/fireblu1 { rgbgen vertex alphagen vertex } }
fireblu2 { program defaultwall#VERTEXLIT diffusemap textures/doom/fireblu2 { rgbgen vertex alphagen vertex } }
firelav2 { program defaultwall#VERTEXLIT diffusemap textures/doom/firelav2 { rgbgen vertex alphagen vertex } }
firelav3 { program defaultwall#VERTEXLIT diffusemap textures/doom/firelav3 { rgbgen vertex alphagen vertex } }
firelava { program defaultwall#VERTEXLIT diffusemap textures/doom/firelava { rgbgen vertex alphagen vertex } }
firemag1 { program defaultwall#VERTEXLIT diffusemap textures/doom/firemag1 { rgbgen vertex alphagen vertex } }
firemag2 { program defaultwall#VERTEXLIT diffusemap textures/doom/firemag2 { rgbgen vertex alphagen vertex } }
firemag3 { program defaultwall#VERTEXLIT diffusemap textures/doom/firemag3 { rgbgen vertex alphagen vertex } }
firewala { program defaultwall#VERTEXLIT diffusemap textures/doom/firewala { rgbgen vertex alphagen vertex } }
firewalb { program defaultwall#VERTEXLIT diffusemap textures/doom/firewalb { rgbgen vertex alphagen vertex } }
firewall { program defaultwall#VERTEXLIT diffusemap textures/doom/firewall { rgbgen vertex alphagen vertex } }
flat1 { program defaultwall#VERTEXLIT diffusemap textures/doom/flat1 { rgbgen vertex alphagen vertex } }
flat10 { program defaultwall#VERTEXLIT diffusemap textures/doom/flat10 { rgbgen vertex alphagen vertex } }
flat14 { program defaultwall#VERTEXLIT diffusemap textures/doom/flat14 { rgbgen vertex alphagen vertex } }
flat17 { program defaultwall#VERTEXLIT diffusemap textures/doom/flat17 { rgbgen vertex alphagen vertex } }
flat18 { program defaultwall#VERTEXLIT diffusemap textures/doom/flat18 { rgbgen vertex alphagen vertex } }
flat19 { program defaultwall#VERTEXLIT diffusemap textures/doom/flat19 { rgbgen vertex alphagen vertex } }
flat1_1 { program defaultwall#VERTEXLIT diffusemap textures/doom/flat1_1 { rgbgen vertex alphagen vertex } }
flat1_2 { program defaultwall#VERTEXLIT diffusemap textures/doom/flat1_2 { rgbgen vertex alphagen vertex } }
flat1_3 { program defaultwall#VERTEXLIT diffusemap textures/doom/flat1_3 { rgbgen vertex alphagen vertex } }
flat2 { program defaultwall#VERTEXLIT diffusemap textures/doom/flat2 { rgbgen vertex alphagen vertex } }
flat20 { program defaultwall#VERTEXLIT diffusemap textures/doom/flat20 { rgbgen vertex alphagen vertex } }
flat22 { program defaultwall#VERTEXLIT diffusemap textures/doom/flat22 { rgbgen vertex alphagen vertex } }
flat23 { program defaultwall#VERTEXLIT diffusemap textures/doom/flat23 { rgbgen vertex alphagen vertex } }
flat3 { program defaultwall#VERTEXLIT diffusemap textures/doom/flat3 { rgbgen vertex alphagen vertex } }
flat4 { program defaultwall#VERTEXLIT diffusemap textures/doom/flat4 { rgbgen vertex alphagen vertex } }
flat5 { program defaultwall#VERTEXLIT diffusemap textures/doom/flat5 { rgbgen vertex alphagen vertex } }
flat5_1 { program defaultwall#VERTEXLIT diffusemap textures/doom/flat5_1 { rgbgen vertex alphagen vertex } }
flat5_2 { program defaultwall#VERTEXLIT diffusemap textures/doom/flat5_2 { rgbgen vertex alphagen vertex } }
flat5_3 { program defaultwall#VERTEXLIT diffusemap textures/doom/flat5_3 { rgbgen vertex alphagen vertex } }
flat5_4 { program defaultwall#VERTEXLIT diffusemap textures/doom/flat5_4 { rgbgen vertex alphagen vertex } }
flat5_5 { program defaultwall#VERTEXLIT diffusemap textures/doom/flat5_5 { rgbgen vertex alphagen vertex } }
flat5_6 { program defaultwall#VERTEXLIT diffusemap textures/doom/flat5_6 { rgbgen vertex alphagen vertex } }
flat5_7 { program defaultwall#VERTEXLIT diffusemap textures/doom/flat5_7 { rgbgen vertex alphagen vertex } }
flat5_8 { program defaultwall#VERTEXLIT diffusemap textures/doom/flat5_8 { rgbgen vertex alphagen vertex } }
flat8 { program defaultwall#VERTEXLIT diffusemap textures/doom/flat8 { rgbgen vertex alphagen vertex } }
flat9 { program defaultwall#VERTEXLIT diffusemap textures/doom/flat9 { rgbgen vertex alphagen vertex } }
floor0_1 { program defaultwall#VERTEXLIT diffusemap textures/doom/floor0_1 { rgbgen vertex alphagen vertex } }
floor0_2 { program defaultwall#VERTEXLIT diffusemap textures/doom/floor0_2 { rgbgen vertex alphagen vertex } }
floor0_3 { program defaultwall#VERTEXLIT diffusemap textures/doom/floor0_3 { rgbgen vertex alphagen vertex } }
floor0_5 { program defaultwall#VERTEXLIT diffusemap textures/doom/floor0_5 { rgbgen vertex alphagen vertex } }
floor0_6 { program defaultwall#VERTEXLIT diffusemap textures/doom/floor0_6 { rgbgen vertex alphagen vertex } }
floor0_7 { program defaultwall#VERTEXLIT diffusemap textures/doom/floor0_7 { rgbgen vertex alphagen vertex } }
floor1_1 { program defaultwall#VERTEXLIT diffusemap textures/doom/floor1_1 { rgbgen vertex alphagen vertex } }
floor1_6 { program defaultwall#VERTEXLIT diffusemap textures/doom/floor1_6 { rgbgen vertex alphagen vertex } }
floor1_7 { program defaultwall#VERTEXLIT diffusemap textures/doom/floor1_7 { rgbgen vertex alphagen vertex } }
floor3_3 { program defaultwall#VERTEXLIT diffusemap textures/doom/floor3_3 { rgbgen vertex alphagen vertex } }
floor4_1 { program defaultwall#VERTEXLIT diffusemap textures/doom/floor4_1 { rgbgen vertex alphagen vertex } }
floor4_5 { program defaultwall#VERTEXLIT diffusemap textures/doom/floor4_5 { rgbgen vertex alphagen vertex } }
floor4_6 { program defaultwall#VERTEXLIT diffusemap textures/doom/floor4_6 { rgbgen vertex alphagen vertex } }
floor4_8 { program defaultwall#VERTEXLIT diffusemap textures/doom/floor4_8 { rgbgen vertex alphagen vertex } }
floor5_1 { program defaultwall#VERTEXLIT diffusemap textures/doom/floor5_1 { rgbgen vertex alphagen vertex } }
floor5_2 { program defaultwall#VERTEXLIT diffusemap textures/doom/floor5_2 { rgbgen vertex alphagen vertex } }
floor5_3 { program defaultwall#VERTEXLIT diffusemap textures/doom/floor5_3 { rgbgen vertex alphagen vertex } }
floor5_4 { program defaultwall#VERTEXLIT diffusemap textures/doom/floor5_4 { rgbgen vertex alphagen vertex } }
floor6_1 { program defaultwall#VERTEXLIT diffusemap textures/doom/floor6_1 { rgbgen vertex alphagen vertex } }
floor6_2 { program defaultwall#VERTEXLIT diffusemap textures/doom/floor6_2 { rgbgen vertex alphagen vertex } }
floor7_1 { program defaultwall#VERTEXLIT diffusemap textures/doom/floor7_1 { rgbgen vertex alphagen vertex } }
floor7_2 { program defaultwall#VERTEXLIT diffusemap textures/doom/floor7_2 { rgbgen vertex alphagen vertex } }
fwater1 { program defaultwall#VERTEXLIT diffusemap textures/doom/fwater1 { rgbgen vertex alphagen vertex } }
fwater2 { program defaultwall#VERTEXLIT diffusemap textures/doom/fwater2 { rgbgen vertex alphagen vertex } }
fwater3 { program defaultwall#VERTEXLIT diffusemap textures/doom/fwater3 { rgbgen vertex alphagen vertex } }
fwater4 { program defaultwall#VERTEXLIT diffusemap textures/doom/fwater4 { rgbgen vertex alphagen vertex } }
f_sky1 { program defaultwall#VERTEXLIT diffusemap textures/doom/f_sky1 { rgbgen vertex alphagen vertex } }
gate1 { program defaultwall#VERTEXLIT diffusemap textures/doom/gate1 { rgbgen vertex alphagen vertex } }
gate2 { program defaultwall#VERTEXLIT diffusemap textures/doom/gate2 { rgbgen vertex alphagen vertex } }
gate3 { program defaultwall#VERTEXLIT diffusemap textures/doom/gate3 { rgbgen vertex alphagen vertex } }
gate4 { program defaultwall#VERTEXLIT diffusemap textures/doom/gate4 { rgbgen vertex alphagen vertex } }
gray1 { program defaultwall#VERTEXLIT diffusemap textures/doom/gray1 { rgbgen vertex alphagen vertex } }
gray2 { program defaultwall#VERTEXLIT diffusemap textures/doom/gray2 { rgbgen vertex alphagen vertex } }
gray4 { program defaultwall#VERTEXLIT diffusemap textures/doom/gray4 { rgbgen vertex alphagen vertex } }
gray5 { program defaultwall#VERTEXLIT diffusemap textures/doom/gray5 { rgbgen vertex alphagen vertex } }
gray7 { program defaultwall#VERTEXLIT diffusemap textures/doom/gray7 { rgbgen vertex alphagen vertex } }
graybig { program defaultwall#VERTEXLIT diffusemap textures/doom/graybig { rgbgen vertex alphagen vertex } }
graydang { program defaultwall#VERTEXLIT diffusemap textures/doom/graydang { rgbgen vertex alphagen vertex } }
graypois { program defaultwall#VERTEXLIT diffusemap textures/doom/graypois { rgbgen vertex alphagen vertex } }
graytall { program defaultwall#VERTEXLIT diffusemap textures/doom/graytall { rgbgen vertex alphagen vertex } }
grayvine { program defaultwall#VERTEXLIT diffusemap textures/doom/grayvine { rgbgen vertex alphagen vertex } }
gstfont1 { program defaultwall#VERTEXLIT diffusemap textures/doom/gstfont1 { rgbgen vertex alphagen vertex } }
gstfont2 { program defaultwall#VERTEXLIT diffusemap textures/doom/gstfont2 { rgbgen vertex alphagen vertex } }
gstfont3 { program defaultwall#VERTEXLIT diffusemap textures/doom/gstfont3 { rgbgen vertex alphagen vertex } }
gstgarg { program defaultwall#VERTEXLIT diffusemap textures/doom/gstgarg { rgbgen vertex alphagen vertex } }
gstlion { program defaultwall#VERTEXLIT diffusemap textures/doom/gstlion { rgbgen vertex alphagen vertex } }
gstone1 { program defaultwall#VERTEXLIT diffusemap textures/doom/gstone1 { rgbgen vertex alphagen vertex } }
gstone2 { program defaultwall#VERTEXLIT diffusemap textures/doom/gstone2 { rgbgen vertex alphagen vertex } }
gstsatyr { program defaultwall#VERTEXLIT diffusemap textures/doom/gstsatyr { rgbgen vertex alphagen vertex } }
gstvine1 { program defaultwall#VERTEXLIT diffusemap textures/doom/gstvine1 { rgbgen vertex alphagen vertex } }
gstvine2 { program defaultwall#VERTEXLIT diffusemap textures/doom/gstvine2 { rgbgen vertex alphagen vertex } }
ickdoor1 { program defaultwall#VERTEXLIT diffusemap textures/doom/ickdoor1 { rgbgen vertex alphagen vertex } }
ickwall1 { program defaultwall#VERTEXLIT diffusemap textures/doom/ickwall1 { rgbgen vertex alphagen vertex } }
ickwall2 { program defaultwall#VERTEXLIT diffusemap textures/doom/ickwall2 { rgbgen vertex alphagen vertex } }
ickwall3 { program defaultwall#VERTEXLIT diffusemap textures/doom/ickwall3 { rgbgen vertex alphagen vertex } }
ickwall4 { program defaultwall#VERTEXLIT diffusemap textures/doom/ickwall4 { rgbgen vertex alphagen vertex } }
ickwall5 { program defaultwall#VERTEXLIT diffusemap textures/doom/ickwall5 { rgbgen vertex alphagen vertex } }
ickwall6 { program defaultwall#VERTEXLIT diffusemap textures/doom/ickwall6 { rgbgen vertex alphagen vertex } }
ickwall7 { program defaultwall#VERTEXLIT diffusemap textures/doom/ickwall7 { rgbgen vertex alphagen vertex } }
lava1 { program defaultwall#VERTEXLIT diffusemap textures/doom/lava1 { rgbgen vertex alphagen vertex } }
lava2 { program defaultwall#VERTEXLIT diffusemap textures/doom/lava2 { rgbgen vertex alphagen vertex } }
lava3 { program defaultwall#VERTEXLIT diffusemap textures/doom/lava3 { rgbgen vertex alphagen vertex } }
lava4 { program defaultwall#VERTEXLIT diffusemap textures/doom/lava4 { rgbgen vertex alphagen vertex } }
lite2 { program defaultwall#VERTEXLIT diffusemap textures/doom/lite2 { rgbgen vertex alphagen vertex } }
lite3 { program defaultwall#VERTEXLIT diffusemap textures/doom/lite3 { rgbgen vertex alphagen vertex } }
lite4 { program defaultwall#VERTEXLIT diffusemap textures/doom/lite4 { rgbgen vertex alphagen vertex } }
lite5 { program defaultwall#VERTEXLIT diffusemap textures/doom/lite5 { rgbgen vertex alphagen vertex } }
lite96 { program defaultwall#VERTEXLIT diffusemap textures/doom/lite96 { rgbgen vertex alphagen vertex } }
liteblu1 { program defaultwall#VERTEXLIT diffusemap textures/doom/liteblu1 { rgbgen vertex alphagen vertex } }
liteblu2 { program defaultwall#VERTEXLIT diffusemap textures/doom/liteblu2 { rgbgen vertex alphagen vertex } }
liteblu3 { program defaultwall#VERTEXLIT diffusemap textures/doom/liteblu3 { rgbgen vertex alphagen vertex } }
liteblu4 { program defaultwall#VERTEXLIT diffusemap textures/doom/liteblu4 { rgbgen vertex alphagen vertex } }
litemet { program defaultwall#VERTEXLIT diffusemap textures/doom/litemet { rgbgen vertex alphagen vertex } }
litered { program defaultwall#VERTEXLIT diffusemap textures/doom/litered { rgbgen vertex alphagen vertex } }
liteston { program defaultwall#VERTEXLIT diffusemap textures/doom/liteston { rgbgen vertex alphagen vertex } }
marbfac2 { program defaultwall#VERTEXLIT diffusemap textures/doom/marbfac2 { rgbgen vertex alphagen vertex } }
marbfac3 { program defaultwall#VERTEXLIT diffusemap textures/doom/marbfac3 { rgbgen vertex alphagen vertex } }
marbface { program defaultwall#VERTEXLIT diffusemap textures/doom/marbface { rgbgen vertex alphagen vertex } }
marble1 { program defaultwall#VERTEXLIT diffusemap textures/doom/marble1 { rgbgen vertex alphagen vertex } }
marble2 { program defaultwall#VERTEXLIT diffusemap textures/doom/marble2 { rgbgen vertex alphagen vertex } }
marble3 { program defaultwall#VERTEXLIT diffusemap textures/doom/marble3 { rgbgen vertex alphagen vertex } }
marblod1 { program defaultwall#VERTEXLIT diffusemap textures/doom/marblod1 { rgbgen vertex alphagen vertex } }
metal { program defaultwall#VERTEXLIT diffusemap textures/doom/metal { rgbgen vertex alphagen vertex } }
metal1 { program defaultwall#VERTEXLIT diffusemap textures/doom/metal1 { rgbgen vertex alphagen vertex } }
mflr8_1 { program defaultwall#VERTEXLIT diffusemap textures/doom/mflr8_1 { rgbgen vertex alphagen vertex } }
mflr8_2 { program defaultwall#VERTEXLIT diffusemap textures/doom/mflr8_2 { rgbgen vertex alphagen vertex } }
mflr8_3 { program defaultwall#VERTEXLIT diffusemap textures/doom/mflr8_3 { rgbgen vertex alphagen vertex } }
mflr8_4 { program defaultwall#VERTEXLIT diffusemap textures/doom/mflr8_4 { rgbgen vertex alphagen vertex } }
midbrn1 { program defaultwall#VERTEXLIT diffusemap textures/doom/midbrn1 { rgbgen vertex alphagen vertex } }
midgrate { program defaultwall#VERTEXLIT diffusemap textures/doom/midgrate { rgbgen vertex alphagen vertex } }
midvine1 { program defaultwall#VERTEXLIT diffusemap textures/doom/midvine1 { rgbgen vertex alphagen vertex } }
midvine2 { program defaultwall#VERTEXLIT diffusemap textures/doom/midvine2 { rgbgen vertex alphagen vertex } }
nukage1 { program defaultwall#VERTEXLIT diffusemap textures/doom/nukage1 { rgbgen vertex alphagen vertex } }
nukage2 { program defaultwall#VERTEXLIT diffusemap textures/doom/nukage2 { rgbgen vertex alphagen vertex } }
nukage3 { program defaultwall#VERTEXLIT diffusemap textures/doom/nukage3 { rgbgen vertex alphagen vertex } }
nuke24 { program defaultwall#VERTEXLIT diffusemap textures/doom/nuke24 { rgbgen vertex alphagen vertex } }
nukedge1 { program defaultwall#VERTEXLIT diffusemap textures/doom/nukedge1 { rgbgen vertex alphagen vertex } }
nukepois { program defaultwall#VERTEXLIT diffusemap textures/doom/nukepois { rgbgen vertex alphagen vertex } }
nukeslad { program defaultwall#VERTEXLIT diffusemap textures/doom/nukeslad { rgbgen vertex alphagen vertex } }
pipe1 { program defaultwall#VERTEXLIT diffusemap textures/doom/pipe1 { rgbgen vertex alphagen vertex } }
pipe2 { program defaultwall#VERTEXLIT diffusemap textures/doom/pipe2 { rgbgen vertex alphagen vertex } }
pipe4 { program defaultwall#VERTEXLIT diffusemap textures/doom/pipe4 { rgbgen vertex alphagen vertex } }
pipe6 { program defaultwall#VERTEXLIT diffusemap textures/doom/pipe6 { rgbgen vertex alphagen vertex } }
planet1 { program defaultwall#VERTEXLIT diffusemap textures/doom/planet1 { rgbgen vertex alphagen vertex } }
plat1 { program defaultwall#VERTEXLIT diffusemap textures/doom/plat1 { rgbgen vertex alphagen vertex } }
redwall { program defaultwall#VERTEXLIT diffusemap textures/doom/redwall { rgbgen vertex alphagen vertex } }
redwall1 { program defaultwall#VERTEXLIT diffusemap textures/doom/redwall1 { rgbgen vertex alphagen vertex } }
rockred1 { program defaultwall#VERTEXLIT diffusemap textures/doom/rockred1 { rgbgen vertex alphagen vertex } }
rockred2 { program defaultwall#VERTEXLIT diffusemap textures/doom/rockred2 { rgbgen vertex alphagen vertex } }
rockred3 { program defaultwall#VERTEXLIT diffusemap textures/doom/rockred3 { rgbgen vertex alphagen vertex } }
sflr6_1 { program defaultwall#VERTEXLIT diffusemap textures/doom/sflr6_1 { rgbgen vertex alphagen vertex } }
sflr6_4 { program defaultwall#VERTEXLIT diffusemap textures/doom/sflr6_4 { rgbgen vertex alphagen vertex } }
sflr7_1 { program defaultwall#VERTEXLIT diffusemap textures/doom/sflr7_1 { rgbgen vertex alphagen vertex } }
sflr7_4 { program defaultwall#VERTEXLIT diffusemap textures/doom/sflr7_4 { rgbgen vertex alphagen vertex } }
shawn1 { program defaultwall#VERTEXLIT diffusemap textures/doom/shawn1 { rgbgen vertex alphagen vertex } }
shawn2 { program defaultwall#VERTEXLIT diffusemap textures/doom/shawn2 { rgbgen vertex alphagen vertex } }
shawn3 { program defaultwall#VERTEXLIT diffusemap textures/doom/shawn3 { rgbgen vertex alphagen vertex } }
skin2 { program defaultwall#VERTEXLIT diffusemap textures/doom/skin2 { rgbgen vertex alphagen vertex } }
skinbord { program defaultwall#VERTEXLIT diffusemap textures/doom/skinbord { rgbgen vertex alphagen vertex } }
skincut { program defaultwall#VERTEXLIT diffusemap textures/doom/skincut { rgbgen vertex alphagen vertex } }
skinedge { program defaultwall#VERTEXLIT diffusemap textures/doom/skinedge { rgbgen vertex alphagen vertex } }
skinface { program defaultwall#VERTEXLIT diffusemap textures/doom/skinface { rgbgen vertex alphagen vertex } }
skinlow { program defaultwall#VERTEXLIT diffusemap textures/doom/skinlow { rgbgen vertex alphagen vertex } }
skinmet1 { program defaultwall#VERTEXLIT diffusemap textures/doom/skinmet1 { rgbgen vertex alphagen vertex } }
skinmet2 { program defaultwall#VERTEXLIT diffusemap textures/doom/skinmet2 { rgbgen vertex alphagen vertex } }
skinscab { program defaultwall#VERTEXLIT diffusemap textures/doom/skinscab { rgbgen vertex alphagen vertex } }
skinsymb { program defaultwall#VERTEXLIT diffusemap textures/doom/skinsymb { rgbgen vertex alphagen vertex } }
skintek1 { program defaultwall#VERTEXLIT diffusemap textures/doom/skintek1 { rgbgen vertex alphagen vertex } }
skintek2 { program defaultwall#VERTEXLIT diffusemap textures/doom/skintek2 { rgbgen vertex alphagen vertex } }
sksnake1 { program defaultwall#VERTEXLIT diffusemap textures/doom/sksnake1 { rgbgen vertex alphagen vertex } }
sksnake2 { program defaultwall#VERTEXLIT diffusemap textures/doom/sksnake2 { rgbgen vertex alphagen vertex } }
skspine1 { program defaultwall#VERTEXLIT diffusemap textures/doom/skspine1 { rgbgen vertex alphagen vertex } }
skspine2 { program defaultwall#VERTEXLIT diffusemap textures/doom/skspine2 { rgbgen vertex alphagen vertex } }
skulwal3 { program defaultwall#VERTEXLIT diffusemap textures/doom/skulwal3 { rgbgen vertex alphagen vertex } }
skulwall { program defaultwall#VERTEXLIT diffusemap textures/doom/skulwall { rgbgen vertex alphagen vertex } }
sky1 { program defaultwall#VERTEXLIT diffusemap textures/doom/sky1 { rgbgen vertex alphagen vertex } }
sky2 { program defaultwall#VERTEXLIT diffusemap textures/doom/sky2 { rgbgen vertex alphagen vertex } }
sky3 { program defaultwall#VERTEXLIT diffusemap textures/doom/sky3 { rgbgen vertex alphagen vertex } }
sky4 { program defaultwall#VERTEXLIT diffusemap textures/doom/sky4 { rgbgen vertex alphagen vertex } }
sladpois { program defaultwall#VERTEXLIT diffusemap textures/doom/sladpois { rgbgen vertex alphagen vertex } }
sladrip1 { program defaultwall#VERTEXLIT diffusemap textures/doom/sladrip1 { rgbgen vertex alphagen vertex } }
sladrip2 { program defaultwall#VERTEXLIT diffusemap textures/doom/sladrip2 { rgbgen vertex alphagen vertex } }
sladrip3 { program defaultwall#VERTEXLIT diffusemap textures/doom/sladrip3 { rgbgen vertex alphagen vertex } }
sladskul { program defaultwall#VERTEXLIT diffusemap textures/doom/sladskul { rgbgen vertex alphagen vertex } }
sladwall { program defaultwall#VERTEXLIT diffusemap textures/doom/sladwall { rgbgen vertex alphagen vertex } }
sp_dude1 { program defaultwall#VERTEXLIT diffusemap textures/doom/sp_dude1 { rgbgen vertex alphagen vertex } }
sp_dude2 { program defaultwall#VERTEXLIT diffusemap textures/doom/sp_dude2 { rgbgen vertex alphagen vertex } }
sp_dude3 { program defaultwall#VERTEXLIT diffusemap textures/doom/sp_dude3 { rgbgen vertex alphagen vertex } }
sp_dude4 { program defaultwall#VERTEXLIT diffusemap textures/doom/sp_dude4 { rgbgen vertex alphagen vertex } }
sp_dude5 { program defaultwall#VERTEXLIT diffusemap textures/doom/sp_dude5 { rgbgen vertex alphagen vertex } }
sp_dude6 { program defaultwall#VERTEXLIT diffusemap textures/doom/sp_dude6 { rgbgen vertex alphagen vertex } }
sp_face1 { program defaultwall#VERTEXLIT diffusemap textures/doom/sp_face1 { rgbgen vertex alphagen vertex } }
sp_hot1 { program defaultwall#VERTEXLIT diffusemap textures/doom/sp_hot1 { rgbgen vertex alphagen vertex } }
sp_rock1 { program defaultwall#VERTEXLIT diffusemap textures/doom/sp_rock1 { rgbgen vertex alphagen vertex } }
sp_rock2 { program defaultwall#VERTEXLIT diffusemap textures/doom/sp_rock2 { rgbgen vertex alphagen vertex } }
starbr2 { program defaultwall#VERTEXLIT diffusemap textures/doom/starbr2 { rgbgen vertex alphagen vertex } }
starg1 { program defaultwall#VERTEXLIT diffusemap textures/doom/starg1 { rgbgen vertex alphagen vertex } }
starg2 { program defaultwall#VERTEXLIT diffusemap textures/doom/starg2 { rgbgen vertex alphagen vertex } }
starg3 { program defaultwall#VERTEXLIT diffusemap textures/doom/starg3 { rgbgen vertex alphagen vertex } }
stargr1 { program defaultwall#VERTEXLIT diffusemap textures/doom/stargr1 { rgbgen vertex alphagen vertex } }
stargr2 { program defaultwall#VERTEXLIT diffusemap textures/doom/stargr2 { rgbgen vertex alphagen vertex } }
startan1 { program defaultwall#VERTEXLIT diffusemap textures/doom/startan1 { rgbgen vertex alphagen vertex } }
startan2 { program defaultwall#VERTEXLIT diffusemap textures/doom/startan2 { rgbgen vertex alphagen vertex } }
startan3 { program defaultwall#VERTEXLIT diffusemap textures/doom/startan3 { rgbgen vertex alphagen vertex } }
step1 { program defaultwall#VERTEXLIT diffusemap textures/doom/step1 { rgbgen vertex alphagen vertex } }
step1a { program defaultwall#VERTEXLIT diffusemap textures/doom/step1a { rgbgen vertex alphagen vertex } }
step2 { program defaultwall#VERTEXLIT diffusemap textures/doom/step2 { rgbgen vertex alphagen vertex } }
step2a { program defaultwall#VERTEXLIT diffusemap textures/doom/step2a { rgbgen vertex alphagen vertex } }
step3 { program defaultwall#VERTEXLIT diffusemap textures/doom/step3 { rgbgen vertex alphagen vertex } }
step4 { program defaultwall#VERTEXLIT diffusemap textures/doom/step4 { rgbgen vertex alphagen vertex } }
step5 { program defaultwall#VERTEXLIT diffusemap textures/doom/step5 { rgbgen vertex alphagen vertex } }
step6 { program defaultwall#VERTEXLIT diffusemap textures/doom/step6 { rgbgen vertex alphagen vertex } }
steplad1 { program defaultwall#VERTEXLIT diffusemap textures/doom/steplad1 { rgbgen vertex alphagen vertex } }
steptop { program defaultwall#VERTEXLIT diffusemap textures/doom/steptop { rgbgen vertex alphagen vertex } }
stone { program defaultwall#VERTEXLIT diffusemap textures/doom/stone { rgbgen vertex alphagen vertex } }
stone2 { program defaultwall#VERTEXLIT diffusemap textures/doom/stone2 { rgbgen vertex alphagen vertex } }
stone3 { program defaultwall#VERTEXLIT diffusemap textures/doom/stone3 { rgbgen vertex alphagen vertex } }
stongarg { program defaultwall#VERTEXLIT diffusemap textures/doom/stongarg { rgbgen vertex alphagen vertex } }
stonpois { program defaultwall#VERTEXLIT diffusemap textures/doom/stonpois { rgbgen vertex alphagen vertex } }
support2 { program defaultwall#VERTEXLIT diffusemap textures/doom/support2 { rgbgen vertex alphagen vertex } }
support3 { program defaultwall#VERTEXLIT diffusemap textures/doom/support3 { rgbgen vertex alphagen vertex } }
sw1blue { program defaultwall#VERTEXLIT diffusemap textures/doom/sw1blue { rgbgen vertex alphagen vertex } }
sw1brcom { program defaultwall#VERTEXLIT diffusemap textures/doom/sw1brcom { rgbgen vertex alphagen vertex } }
sw1brn1 { program defaultwall#VERTEXLIT diffusemap textures/doom/sw1brn1 { rgbgen vertex alphagen vertex } }
sw1brn2 { program defaultwall#VERTEXLIT diffusemap textures/doom/sw1brn2 { rgbgen vertex alphagen vertex } }
sw1brngn { program defaultwall#VERTEXLIT diffusemap textures/doom/sw1brngn { rgbgen vertex alphagen vertex } }
sw1brown { program defaultwall#VERTEXLIT diffusemap textures/doom/sw1brown { rgbgen vertex alphagen vertex } }
sw1cmt { program defaultwall#VERTEXLIT diffusemap textures/doom/sw1cmt { rgbgen vertex alphagen vertex } }
sw1comm { program defaultwall#VERTEXLIT diffusemap textures/doom/sw1comm { rgbgen vertex alphagen vertex } }
sw1comp { program defaultwall#VERTEXLIT diffusemap textures/doom/sw1comp { rgbgen vertex alphagen vertex } }
sw1dirt { program defaultwall#VERTEXLIT diffusemap textures/doom/sw1dirt { rgbgen vertex alphagen vertex } }
sw1exit { program defaultwall#VERTEXLIT diffusemap textures/doom/sw1exit { rgbgen vertex alphagen vertex } }
sw1garg { program defaultwall#VERTEXLIT diffusemap textures/doom/sw1garg { rgbgen vertex alphagen vertex } }
sw1gray { program defaultwall#VERTEXLIT diffusemap textures/doom/sw1gray { rgbgen vertex alphagen vertex } }
sw1gray1 { program defaultwall#VERTEXLIT diffusemap textures/doom/sw1gray1 { rgbgen vertex alphagen vertex } }
sw1gston { program defaultwall#VERTEXLIT diffusemap textures/doom/sw1gston { rgbgen vertex alphagen vertex } }
sw1hot { program defaultwall#VERTEXLIT diffusemap textures/doom/sw1hot { rgbgen vertex alphagen vertex } }
sw1lion { program defaultwall#VERTEXLIT diffusemap textures/doom/sw1lion { rgbgen vertex alphagen vertex } }
sw1metal { program defaultwall#VERTEXLIT diffusemap textures/doom/sw1metal { rgbgen vertex alphagen vertex } }
sw1pipe { program defaultwall#VERTEXLIT diffusemap textures/doom/sw1pipe { rgbgen vertex alphagen vertex } }
sw1satyr { program defaultwall#VERTEXLIT diffusemap textures/doom/sw1satyr { rgbgen vertex alphagen vertex } }
sw1skin { program defaultwall#VERTEXLIT diffusemap textures/doom/sw1skin { rgbgen vertex alphagen vertex } }
sw1slad { program defaultwall#VERTEXLIT diffusemap textures/doom/sw1slad { rgbgen vertex alphagen vertex } }
sw1starg { program defaultwall#VERTEXLIT diffusemap textures/doom/sw1starg { rgbgen vertex alphagen vertex } }
sw1ston1 { program defaultwall#VERTEXLIT diffusemap textures/doom/sw1ston1 { rgbgen vertex alphagen vertex } }
sw1ston2 { program defaultwall#VERTEXLIT diffusemap textures/doom/sw1ston2 { rgbgen vertex alphagen vertex } }
sw1stone { program defaultwall#VERTEXLIT diffusemap textures/doom/sw1stone { rgbgen vertex alphagen vertex } }
sw1strtn { program defaultwall#VERTEXLIT diffusemap textures/doom/sw1strtn { rgbgen vertex alphagen vertex } }
sw1vine { program defaultwall#VERTEXLIT diffusemap textures/doom/sw1vine { rgbgen vertex alphagen vertex } }
sw1wood { program defaultwall#VERTEXLIT diffusemap textures/doom/sw1wood { rgbgen vertex alphagen vertex } }
sw2blue { program defaultwall#VERTEXLIT diffusemap textures/doom/sw2blue { rgbgen vertex alphagen vertex } }
sw2brcom { program defaultwall#VERTEXLIT diffusemap textures/doom/sw2brcom { rgbgen vertex alphagen vertex } }
sw2brn1 { program defaultwall#VERTEXLIT diffusemap textures/doom/sw2brn1 { rgbgen vertex alphagen vertex } }
sw2brn2 { program defaultwall#VERTEXLIT diffusemap textures/doom/sw2brn2 { rgbgen vertex alphagen vertex } }
sw2brngn { program defaultwall#VERTEXLIT diffusemap textures/doom/sw2brngn { rgbgen vertex alphagen vertex } }
sw2brown { program defaultwall#VERTEXLIT diffusemap textures/doom/sw2brown { rgbgen vertex alphagen vertex } }
sw2cmt { program defaultwall#VERTEXLIT diffusemap textures/doom/sw2cmt { rgbgen vertex alphagen vertex } }
sw2comm { program defaultwall#VERTEXLIT diffusemap textures/doom/sw2comm { rgbgen vertex alphagen vertex } }
sw2comp { program defaultwall#VERTEXLIT diffusemap textures/doom/sw2comp { rgbgen vertex alphagen vertex } }
sw2dirt { program defaultwall#VERTEXLIT diffusemap textures/doom/sw2dirt { rgbgen vertex alphagen vertex } }
sw2exit { program defaultwall#VERTEXLIT diffusemap textures/doom/sw2exit { rgbgen vertex alphagen vertex } }
sw2garg { program defaultwall#VERTEXLIT diffusemap textures/doom/sw2garg { rgbgen vertex alphagen vertex } }
sw2gray { program defaultwall#VERTEXLIT diffusemap textures/doom/sw2gray { rgbgen vertex alphagen vertex } }
sw2gray1 { program defaultwall#VERTEXLIT diffusemap textures/doom/sw2gray1 { rgbgen vertex alphagen vertex } }
sw2gston { program defaultwall#VERTEXLIT diffusemap textures/doom/sw2gston { rgbgen vertex alphagen vertex } }
sw2hot { program defaultwall#VERTEXLIT diffusemap textures/doom/sw2hot { rgbgen vertex alphagen vertex } }
sw2lion { program defaultwall#VERTEXLIT diffusemap textures/doom/sw2lion { rgbgen vertex alphagen vertex } }
sw2metal { program defaultwall#VERTEXLIT diffusemap textures/doom/sw2metal { rgbgen vertex alphagen vertex } }
sw2pipe { program defaultwall#VERTEXLIT diffusemap textures/doom/sw2pipe { rgbgen vertex alphagen vertex } }
sw2satyr { program defaultwall#VERTEXLIT diffusemap textures/doom/sw2satyr { rgbgen vertex alphagen vertex } }
sw2skin { program defaultwall#VERTEXLIT diffusemap textures/doom/sw2skin { rgbgen vertex alphagen vertex } }
sw2slad { program defaultwall#VERTEXLIT diffusemap textures/doom/sw2slad { rgbgen vertex alphagen vertex } }
sw2starg { program defaultwall#VERTEXLIT diffusemap textures/doom/sw2starg { rgbgen vertex alphagen vertex } }
sw2ston1 { program defaultwall#VERTEXLIT diffusemap textures/doom/sw2ston1 { rgbgen vertex alphagen vertex } }
sw2ston2 { program defaultwall#VERTEXLIT diffusemap textures/doom/sw2ston2 { rgbgen vertex alphagen vertex } }
sw2stone { program defaultwall#VERTEXLIT diffusemap textures/doom/sw2stone { rgbgen vertex alphagen vertex } }
sw2strtn { program defaultwall#VERTEXLIT diffusemap textures/doom/sw2strtn { rgbgen vertex alphagen vertex } }
sw2vine { program defaultwall#VERTEXLIT diffusemap textures/doom/sw2vine { rgbgen vertex alphagen vertex } }
sw2wood { program defaultwall#VERTEXLIT diffusemap textures/doom/sw2wood { rgbgen vertex alphagen vertex } }
tekwall1 { program defaultwall#VERTEXLIT diffusemap textures/doom/tekwall1 { rgbgen vertex alphagen vertex } }
tekwall2 { program defaultwall#VERTEXLIT diffusemap textures/doom/tekwall2 { rgbgen vertex alphagen vertex } }
tekwall3 { program defaultwall#VERTEXLIT diffusemap textures/doom/tekwall3 { rgbgen vertex alphagen vertex } }
tekwall4 { program defaultwall#VERTEXLIT diffusemap textures/doom/tekwall4 { rgbgen vertex alphagen vertex } }
tekwall5 { program defaultwall#VERTEXLIT diffusemap textures/doom/tekwall5 { rgbgen vertex alphagen vertex } }
tlite6_1 { program defaultwall#VERTEXLIT diffusemap textures/doom/tlite6_1 { rgbgen vertex alphagen vertex } }
tlite6_4 { program defaultwall#VERTEXLIT diffusemap textures/doom/tlite6_4 { rgbgen vertex alphagen vertex } }
tlite6_5 { program defaultwall#VERTEXLIT diffusemap textures/doom/tlite6_5 { rgbgen vertex alphagen vertex } }
tlite6_6 { program defaultwall#VERTEXLIT diffusemap textures/doom/tlite6_6 { rgbgen vertex alphagen vertex } }
wood1 { program defaultwall#VERTEXLIT diffusemap textures/doom/wood1 { rgbgen vertex alphagen vertex } }
wood3 { program defaultwall#VERTEXLIT diffusemap textures/doom/wood3 { rgbgen vertex alphagen vertex } }
wood4 { program defaultwall#VERTEXLIT diffusemap textures/doom/wood4 { rgbgen vertex alphagen vertex } }
wood5 { program defaultwall#VERTEXLIT diffusemap textures/doom/wood5 { rgbgen vertex alphagen vertex } }
woodgarg { program defaultwall#VERTEXLIT diffusemap textures/doom/woodgarg { rgbgen vertex alphagen vertex } }
woodskul { program defaultwall#VERTEXLIT diffusemap textures/doom/woodskul { rgbgen vertex alphagen vertex } }