floor_blue_a { program defaultwall diffusemap textures/lq_dev/floor_blue_a }
floor_blue_b { program defaultwall diffusemap textures/lq_dev/floor_blue_b }
floor_blue_c { program defaultwall diffusemap textures/lq_dev/floor_blue_c }
floor_brown_a { program defaultwall diffusemap textures/lq_dev/floor_brown_a }
floor_brown_b { program defaultwall diffusemap textures/lq_dev/floor_brown_b }
floor_brown_c { program defaultwall diffusemap textures/lq_dev/floor_brown_c }
floor_green_a { program defaultwall diffusemap textures/lq_dev/floor_green_a }
floor_green_b { program defaultwall diffusemap textures/lq_dev/floor_green_b }
floor_green_c { program defaultwall diffusemap textures/lq_dev/floor_green_c }
floor_grey_a { program defaultwall diffusemap textures/lq_dev/floor_grey_a }
floor_grey_b { program defaultwall diffusemap textures/lq_dev/floor_grey_b }
floor_grey_c { program defaultwall diffusemap textures/lq_dev/floor_grey_c }
floor_olive_a { program defaultwall diffusemap textures/lq_dev/floor_olive_a }
floor_olive_b { program defaultwall diffusemap textures/lq_dev/floor_olive_b }
floor_olive_c { program defaultwall diffusemap textures/lq_dev/floor_olive_c }
floor_orange_a { program defaultwall diffusemap textures/lq_dev/floor_orange_a }
floor_orange_b { program defaultwall diffusemap textures/lq_dev/floor_orange_b }
floor_orange_c { program defaultwall diffusemap textures/lq_dev/floor_orange_c }
floor_pink_a { program defaultwall diffusemap textures/lq_dev/floor_pink_a }
floor_pink_b { program defaultwall diffusemap textures/lq_dev/floor_pink_b }
floor_pink_c { program defaultwall diffusemap textures/lq_dev/floor_pink_c }
floor_purple_a { program defaultwall diffusemap textures/lq_dev/floor_purple_a }
floor_purple_b { program defaultwall diffusemap textures/lq_dev/floor_purple_b }
floor_purple_c { program defaultwall diffusemap textures/lq_dev/floor_purple_c }
floor_red_a { program defaultwall diffusemap textures/lq_dev/floor_red_a }
floor_red_b { program defaultwall diffusemap textures/lq_dev/floor_red_b }
floor_red_c { program defaultwall diffusemap textures/lq_dev/floor_red_c }
floor_tan_a { program defaultwall diffusemap textures/lq_dev/floor_tan_a }
floor_tan_b { program defaultwall diffusemap textures/lq_dev/floor_tan_b }
floor_tan_c { program defaultwall diffusemap textures/lq_dev/floor_tan_c }
floor_yellow_a { program defaultwall diffusemap textures/lq_dev/floor_yellow_a }
floor_yellow_b { program defaultwall diffusemap textures/lq_dev/floor_yellow_b }
floor_yellow_c { program defaultwall diffusemap textures/lq_dev/floor_yellow_c }
wall_blue_a { program defaultwall diffusemap textures/lq_dev/wall_blue_a }
wall_blue_b { program defaultwall diffusemap textures/lq_dev/wall_blue_b }
wall_blue_c { program defaultwall diffusemap textures/lq_dev/wall_blue_c }
wall_brown_a { program defaultwall diffusemap textures/lq_dev/wall_brown_a }
wall_brown_b { program defaultwall diffusemap textures/lq_dev/wall_brown_b }
wall_brown_c { program defaultwall diffusemap textures/lq_dev/wall_brown_c }
wall_green_a { program defaultwall diffusemap textures/lq_dev/wall_green_a }
wall_green_b { program defaultwall diffusemap textures/lq_dev/wall_green_b }
wall_green_c { program defaultwall diffusemap textures/lq_dev/wall_green_c }
wall_grey_a { program defaultwall diffusemap textures/lq_dev/wall_grey_a }
wall_grey_b { program defaultwall diffusemap textures/lq_dev/wall_grey_b }
wall_grey_c { program defaultwall diffusemap textures/lq_dev/wall_grey_c }
wall_olive_a { program defaultwall diffusemap textures/lq_dev/wall_olive_a }
wall_olive_b { program defaultwall diffusemap textures/lq_dev/wall_olive_b }
wall_olive_c { program defaultwall diffusemap textures/lq_dev/wall_olive_c }
wall_orange_a { program defaultwall diffusemap textures/lq_dev/wall_orange_a }
wall_orange_b { program defaultwall diffusemap textures/lq_dev/wall_orange_b }
wall_orange_c { program defaultwall diffusemap textures/lq_dev/wall_orange_c }
wall_pink_a { program defaultwall diffusemap textures/lq_dev/wall_pink_a }
wall_pink_b { program defaultwall diffusemap textures/lq_dev/wall_pink_b }
wall_pink_c { program defaultwall diffusemap textures/lq_dev/wall_pink_c }
wall_purple_a { program defaultwall diffusemap textures/lq_dev/wall_purple_a }
wall_purple_b { program defaultwall diffusemap textures/lq_dev/wall_purple_b }
wall_purple_c { program defaultwall diffusemap textures/lq_dev/wall_purple_c }
wall_red_a { program defaultwall diffusemap textures/lq_dev/wall_red_a }
wall_red_b { program defaultwall diffusemap textures/lq_dev/wall_red_b }
wall_red_c { program defaultwall diffusemap textures/lq_dev/wall_red_c }
wall_tan_a { program defaultwall diffusemap textures/lq_dev/wall_tan_a }
wall_tan_b { program defaultwall diffusemap textures/lq_dev/wall_tan_b }
wall_tan_c { program defaultwall diffusemap textures/lq_dev/wall_tan_c }
wall_yellow_a { program defaultwall diffusemap textures/lq_dev/wall_yellow_a }
wall_yellow_b { program defaultwall diffusemap textures/lq_dev/wall_yellow_b }
wall_yellow_c { program defaultwall diffusemap textures/lq_dev/wall_yellow_c }